default:
  # NOTE: This is a private image, it requires the DOCKER_AUTH_CONFIG CI variable to be set.
  image: localghost345/esp-idf:1.0

build-job:
  script:
    - Meta/build_image.sh

  artifacts:
    paths:
      - "build"

test-job:
  script:
    - Meta/run_tests.sh linux
