[package]
name = "cope_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macaddr = { version = "1.0.1" }
byte-unit = { version = "5.0.3" }
