nodes = [
    ["A", "000000000000"],
    ["B", "000000000000"],
    ["C", "000000000000"],
    ["D", "000000000000"],
]

relay = "B"

black_list = [
    ["A", ["C"]],
    ["C", ["A"]],
    ["D", ["A", "B", "C"]],
]
