# 34:85:18:b8:38:ec
nodes = [
    ["A", "348518b838ec"],
    ["B", "000000000000"],
    ["C", "000000000000"],
]

relay = "B"

rx_whitelist = [
    ["A", ["B"]],
    ["B", ["A", "C"]],
    ["C", ["B"]],
]

tx_whitelist = [
    ["A", ["C"]],
    ["B", ["A", "C"]],
    ["C", ["A"]],
]

traffic_generators = [
    [
        "A",
        "Periodic(1s)",
    ],
    [
        "B",
        "None",
    ],
    [
        "C",
        "Periodic(1s)",
    ],
]
