nodes = [["A", "348518b838ec"], ["B", "000000000000"], ["C", "000000000000"]]

relay = "B"

rx_whitelist = [["A", ["B"]], ["B", ["A", "C"]], ["C", ["B"]]]

tx_whitelist = [["A", ["C"]], ["B", ["A", "C"]], ["C", ["A"]]]

traffic_generators = [["A", "Random(5kb)"], ["B", "None"], ["C", "Random(5kb)"]]

simulator_packet_loss = 0.0
round_trip_time = "1.5s"
packet_pool_size = 8
control_packet_duration = "200ms"
max_retrans_amount = 2
use_coding = true
stats_log_duration = "1s"
log_node_stats = true
log_espnow_stats = true
