nodes = [
    ["A", "348518b838ec"],
    ["B", "000000000000"],
    ["C", "000000000000"],
    ["D", "000000000000"],
]

relay = "B"

rx_whitelist = [
    ["A", ["B"]],
    ["B", ["A", "C"]],
    ["C", ["B"]],
    ["D", ["A", "B", "C"]]
]

tx_whitelist = [
    ["A", ["C"]],
    ["B", ["A", "C"]],
    ["C", ["A"]],
    ["D", ["A", "C"]]
]

traffic_generators = [
    [
        "A",
        "Random(1)",
    ],
    [
        "B",
        "None",
    ],
    [
        "C",
        "Random(1)",
    ],
    [
        "D",
        "None",
    ],
]
