# TODO: Change to MAC addresses of our ESPs!
nodes = [
    [
        "A",
        "34:85:18:b8:3c:04",
    ],
    [
        "B",
        "34:85:18:b8:38:ec",
    ],
    [
        "C",
        "48:27:e2:3b:32:d4",
    ],
]

relay = "B"

rx_whitelist = [["A", ["B"]], ["B", ["A", "C"]], ["C", ["B"]]]

tx_whitelist = [["A", ["C"]], ["B", ["A", "C"]], ["C", ["A"]]]

traffic_generators = [
    [
        "A",
        "Periodic(1s)",
    ],
    [
        "B",
        "None",
    ],
    [
        "C",
        "Periodic(1s)",
    ],
]

simulator_packet_loss = 0.0
round_trip_time = "1000ms"
packet_pool_size = 8
control_packet_duration = "200ms"
max_retrans_amount = 2
use_coding = true
