nodes = [["A", "48:27:e2:3b:30:58"], ["B", "48:27:e2:3b:31:04"]]
relay = "B"

rx_whitelist = [["A", ["B"]], ["B", ["A"]]]

tx_whitelist = [["A", ["B"]], ["B", ["A"]]]

traffic_generators = [["A", "Random(1Mbit)"], ["B", "None"]]

simulator_packet_loss = 0.0
round_trip_time = "20ms"
packet_pool_size = 8
control_packet_duration = "200ms"
max_retrans_amount = 2
use_coding = false
stats_log_duration = "1s"
log_node_stats = true
log_espnow_stats = true
